"""Produce proposal figures through the Codex CLI so no OpenAI API key is needed.

The live transport in ``proposal_images`` posts to the images endpoint with a raw
credential. A node that only has a Codex OAuth session has no such key, so this
transport drives ``codex exec`` instead and lets the CLI's own built-in
``image_gen`` tool carry the billing identity. The CLI reads its session from
``~/.codex/auth.json``, which is why the child process inherits the environment.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from .proposal_images import ImageGenerationError, ImageInputError


DEFAULT_BINARY: Final = "codex"
DEFAULT_QUALITY: Final = "medium"
DEFAULT_SIZE: Final = "1024x1024"
_QUALITIES: Final = ("low", "medium", "high", "auto")
_PNG_MAGIC: Final = b"\x89PNG\r\n\x1a\n"
_ERROR_TAIL: Final = 500
# Coarse-timestamp filesystems can stamp a file written after the run started
# with a marginally earlier mtime. One second absorbs that without widening the
# window enough to admit an image left by an earlier call.
_MTIME_SLACK: Final = 1.0


@dataclass(frozen=True, slots=True)
class _Settings:
    binary: str
    quality: str
    size: str


def _settings(params: dict[str, str]) -> _Settings:
    binary = os.environ.get("PROPOSAL_IMAGE_CODEX_BIN", DEFAULT_BINARY).strip()
    quality = os.environ.get("PROPOSAL_IMAGE_QUALITY", DEFAULT_QUALITY).strip().lower()
    if quality not in _QUALITIES:
        raise ImageInputError(
            "PROPOSAL_IMAGE_QUALITY must be low, medium, high or auto"
        )
    return _Settings(binary or DEFAULT_BINARY, quality, params.get("size", DEFAULT_SIZE))


def _instruction(prompt: str, settings: _Settings, target: Path) -> str:
    return (
        "Call your built-in image_gen tool exactly once. Generate 1 image with "
        f"size {settings.size} and quality {settings.quality} for this prompt:\n"
        f"{prompt}\n"
        f"Then copy the generated PNG to {target} and print that path as your "
        "last line. Do not create, edit or delete any other file, and do not "
        "run any other tool."
    )


def _run(
    settings: _Settings, prompt: str, directory: Path, timeout: float
) -> subprocess.CompletedProcess[str]:
    command = [
        settings.binary,
        "exec",
        _instruction(prompt, settings, directory / "figure.png"),
        "-C",
        str(directory),
        "-s",
        "workspace-write",
        "-c",
        'model_reasoning_effort="low"',
        "--skip-git-repo-check",
    ]
    try:
        return subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
            env=dict(os.environ),
        )
    except subprocess.TimeoutExpired as error:
        raise ImageGenerationError(
            f"codex image run exceeded {timeout:g}s"
        ) from error
    except OSError as error:
        raise ImageGenerationError(f"codex image run could not start: {error}") from error


def _png_bytes(path: Path) -> bytes | None:
    if path.is_symlink() or not path.is_file():
        return None
    try:
        content = path.read_bytes()
    except OSError:
        return None
    return content if content.startswith(_PNG_MAGIC) else None


def _generated_image(started: float) -> bytes | None:
    """Recover an image the CLI saved to its own gallery instead of the workdir."""
    home = Path(os.environ.get("CODEX_HOME", "~/.codex")).expanduser()
    try:
        candidates = sorted(
            (
                (path.stat().st_mtime, path)
                for path in (home / "generated_images").rglob("ig_*.png")
                if path.is_file() and not path.is_symlink()
            ),
            reverse=True,
        )
    except OSError:
        return None
    for modified, path in candidates:
        if modified + _MTIME_SLACK < started:
            break
        content = _png_bytes(path)
        if content is not None:
            return content
    return None


def _failure(completed: subprocess.CompletedProcess[str]) -> str:
    output = (completed.stderr or completed.stdout or "").strip()
    return (
        f"codex image run produced no PNG (rc={completed.returncode}): "
        f"{output[-_ERROR_TAIL:]}"
    )


def codex_transport(
    prompt: str, model: str, params: dict[str, str], timeout: float
) -> bytes:
    """Return one PNG generated by the Codex CLI under its OAuth session."""
    del model  # The CLI picks the image model its own session is entitled to.
    settings = _settings(params)
    directory = Path(tempfile.mkdtemp(prefix="proposal-image-codex-"))
    directory.chmod(0o700)
    started = time.time()
    try:
        completed = _run(settings, prompt, directory, timeout)
        content = _png_bytes(directory / "figure.png") or _generated_image(started)
        if content is None:
            raise ImageGenerationError(_failure(completed))
        return content
    finally:
        shutil.rmtree(directory, ignore_errors=True)
